# Generated by Django 4.2.2 on 2025-11-18 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_subscriptionplan_usersubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('tax_id', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('loan_type', models.CharField(choices=[('personal', 'Personal Loan'), ('business', 'Business Loan'), ('education', 'Education Loan'), ('mortgage', 'Mortgage'), ('emergency', 'Emergency Loan')], default='personal', max_length=20)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_range_min', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_range_max', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reason', models.TextField()),
                ('identification_image', models.ImageField(upload_to='loans/identification/')),
                ('proof_of_income', models.ImageField(upload_to='loans/income_proof/')),
                ('additional_documents', models.ImageField(blank=True, null=True, upload_to='loans/additional/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('under_review', 'Under Review')], default='pending', max_length=20)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GrantApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('tax_id', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('grant_type', models.CharField(choices=[('education', 'Education Grant'), ('research', 'Research Grant'), ('business', 'Business Grant'), ('community', 'Community Project Grant'), ('nonprofit', 'Non-Profit Grant')], default='education', max_length=20)),
                ('organization_name', models.CharField(blank=True, max_length=255)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_range_min', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_range_max', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reason', models.TextField()),
                ('project_description', models.TextField(blank=True)),
                ('identification_image', models.ImageField(upload_to='grants/identification/')),
                ('proposal_document', models.ImageField(upload_to='grants/proposals/')),
                ('additional_documents', models.ImageField(blank=True, null=True, upload_to='grants/additional/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('under_review', 'Under Review')], default='pending', max_length=20)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
